export const ownerSelectors = {
    firstNameTexbox: '#firstName',
    lastNameTexbox: '#lastName',
    addressTexbox: '#address',
    cityTexbox: '#city',
    phoneTexbox: '#telephone',
    findOwnerButton: 'button[type="submit"]',
    addOwnerButton: 'a.btn.btn-primary',
    itemsOwnersTable: 'table#owners tbody tr',
    nameColOwnerTable: 'td:nth-child(1) a',
    addressColOwnerTable: 'td:nth-child(2)',
    cityColOwnerTable: 'td:nth-child(3)',
    phoneColOwnerTable: 'td:nth-child(4)',
    petsColOwnerTable: 'td:nth-child(5)',
    saveOwnerButton: '//button[contains(text(), "Add Owner")]',
    lastPageOwners: 'a[title="Last"]',
    editOwnerButton: 'h2 ~ a[href*="edit"]',
    updatedOwnerButton: '//button[contains(text(), "Update Owner")]',
    successMessageAlert: '#success-message',
    itemsAddressOwnerInfo: '//div/table[1]/tbody/tr[2]/td'
};